// src/components/Navbar.vue
<template>
  <nav class="madoc-navbar">
    <ul class="madoc-navbar-list left">
      <li
        v-for="(link, index) in navbar.links"
        :key="index">
        <router-link :to="link.path">
          {{ link.title }}
        </router-link>
      </li>
    </ul>
    <ul class="madoc-navbar-list right">
      <li v-if="navbar.github" class="icon">
				<a :href="navbar.github.link" target='_blank'>
          <eva-icon name="github" animation="pulse" width="30" height="30"></eva-icon>
				</a>
			</li>
      <li class="icon menu" @click="showColorPicker = !showColorPicker">
        <div class="icon-container">
          <eva-icon name="color-palette" animation="pulse" width="30" height="30"></eva-icon>
        </div>
        <ColorPicker v-show="showColorPicker"></ColorPicker>
      </li>
    </ul>
  </nav>
</template>

<script>
import { EvaIcon } from 'vue-eva-icons';
import ColorPicker from '@/components/ColorPicker.vue';
export default {
  name: 'Navbar',
  components: {
    ColorPicker,
    [EvaIcon.name]: EvaIcon
  },
  data () {
    return {
      showColorPicker: false
    };
  },
  computed: {
    page () {
      return this.$store.getters.pages[this.$route.name];
    },
    navbar () {
      return this.page.metadata.navbar;
    }
  }
};
</script>

<style lang="scss" scoped>
nav.madoc-navbar {
  display: flex;
  align-items: center;
  border-bottom: 1px solid var(--madoc-heading-underline-color);
  > ul.madoc-navbar-list {
    display: flex;
    align-items: center;
    margin: 0;
    padding: 0;
    list-style: none;
    height: 50px;
    line-height: 50px;
    &:first-child {
      margin-left: 10px;
    }
    &.right {
      margin-left: auto;
    }
    > li {
      height: 50px;
      &:last-child {
        margin-right: 10px;
      }
      &.menu {
        cursor: pointer;
        user-select: none;
        > div.icon-container {
          height: 100%;
          display: flex;
          align-items: center;
          > i {
            display: flex;
            align-items: center;
            fill: var(--madoc-navbar-icon-color);
          }
        }
      }
      > a {
        height: 50px;
        color: inherit;
        text-decoration: none;
        display: flex;
        align-items: center;
        padding: 0 1em;
        &.router-link-exact-active {
          border-bottom: 2px solid var(--madoc-accent);
        }
        > i {
          display: flex;
          align-items: center;
          fill: var(--madoc-navbar-icon-color);
        }
      }
    }
  }
}
</style>

// src/components/Navbar.svelte
<script>
	import { stores } from '@sapper/app';
	import { onMount } from 'svelte';
	import eva from 'eva-icons';
	import ColorPicker from './ColorPicker.svelte';

	const { page } = stores();
	export let navbar;

	let openTogglePicker = false;

	onMount(() => {
		eva.replace();
	});
	function toggleColorPicker () {
		openTogglePicker = !openTogglePicker;
	}
</script>

<style lang="scss" scoped>
	nav {
		display: flex;
		align-items: center;
		border-bottom: 1px solid var(--madoc-heading-underline-color);
		font-weight: 400;
		transition: border .25s ease-out;
		> ul {
			display: flex;
			align-items: center;
			margin: 0;
			padding: 0;
			list-style: none;
			height: 50px;
			line-height: 50px;
			> li {
				height: 100%;
				> a {
					height: 100%;
				}
				&:first-child {
					margin-left: 10px;
				}
			}
			&.links {
				> li {
					border-bottom: 2px solid transparent;
					&:hover, &.selected {
						border-bottom: 2px solid var(--madoc-accent);
					}
					> a {
						color: inherit;
						text-decoration: none;
						display: block;
						padding: 0 1em;
					}
				}
			}
			&.options {
				margin-left: auto;
				> li.icon {
					position: relative;
					display: inline-block;
					padding: 0 5px;
					fill: var(--madoc-navbar-icon-color);
					> div.icon-container {
						height: 100%;
						display: flex;
						align-items: center;
					}
					cursor: pointer;
					&:hover {
						fill: var(--madoc-navbar-icon-hover-color);
					}
					&.github {
						> a {					
							display: flex;
							align-items: center;
							fill: var(--madoc-navbar-icon-color);
							&:hover {
								fill: var(--madoc-navbar-icon-hover-color);
							}
						}
					}
				}
				> li:last-child {
					padding-right: 10px;
				}
			}
		}
	}
</style>

<nav>
	<ul class='links'>
		{#each navbar.links as link}
			<li class:selected={$page.path === link.path}><a rel=prefetch href={link.path}>{link.title}</a></li>
		{/each}
	</ul>
	<ul class='options'>
		{#if navbar.github}
			<li class='github icon'>
				<a href={navbar.github.link} target='_blank'>
					<i data-eva="github" data-eva-height="30" data-eva-width="30" data-eva-animation="pulse" data-eva-hover="false" data-eva-infinite="false"></i>
				</a>
			</li>
			{/if}
		<li class='icon' on:click={toggleColorPicker}>
			<div class='icon-container'>
				<i data-eva="color-palette" data-eva-height="30" data-eva-width="30" data-eva-animation="pulse" data-eva-hover="false" data-eva-infinite="false"></i>
			</div>
			<ColorPicker active={openTogglePicker}></ColorPicker>
		</li>
	</ul>
</nav>
